name: Changelog

on:
  release:
    types: 
      - published

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ci/sync-changelog
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Update CHANGELOG.md
        run: ./gradlew updateChangelog -PreleaseBody="${{ github.event.release.body }}"
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: "Update CHANGELOG.md"
          add: "CHANGELOG.md"
          ref: ci/sync-changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
